name: Move Issue when PR merged

on:
  pull_request:
    types: [closed]

jobs:
  move-to-in-review:
    runs-on: ubuntu-latest
    name: Move to In review column
    if: ${{ github.event.pull_request.merged }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get issue id
        id: get-issue-id
        run: |
          branch_name="${{ github.head_ref }}"
          regex="(feature|bugfix)/([0-9][0-9]*)"
          if [[ $branch_name =~ $regex ]]; then
            issue_id=${BASH_REMATCH[2]}
          fi
          echo ::set-output name=issue_id::$issue_id

      - name: Move to In review
        if: ${{ steps.get-issue-id.outputs.issue_id }}
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: Common Actions
          column-name: In review
          issue-number: ${{ steps.get-issue-id.outputs.issue_id }}
