name: tag project based on gradle version

on:
  workflow_call:
    inputs:
      gradle_location:
        description: 'full path to build.gradle file'
        required: false
        default: 'build.gradle'
        type: string
    secrets:
      checkout_token:
        description: 'workflow token for checkout and push'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    # run job if previous was successful
    # don`t run if commit message starts with '[RELEASE]' to prevent infinite loop
    if: ${{ github.event.workflow_run.conclusion == 'success' && !startsWith(github.event.head_commit.message, '[RELEASE]') }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.checkout_token }}

      - name: tag version
        run: |
          version=$(egrep "^version = (.*)$" "${{ inputs.gradle_location }}" |awk -F"'" '{print $2}')
          #
          # git tag current version
          #
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag -a "$version" -m "[RELEASE] crete new tag $version"
          git push --tags origin
